// tslint:disable
/**
 * Markku portal API
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: markku@futurice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    StartCommandTrainingParams,
    StartCommandTrainingParamsFromJSON,
    StartCommandTrainingParamsToJSON,
} from './';

/**
 * 
 * @export
 * @interface StartCommand
 */
export interface StartCommand {
    /**
     * 
     * @type {string}
     * @memberof StartCommand
     */
    command: StartCommandCommandEnum;
    /**
     * 
     * @type {StartCommandTrainingParams}
     * @memberof StartCommand
     */
    trainingParams: StartCommandTrainingParams;
}

export function StartCommandFromJSON(json: any): StartCommand {
    return {
        'command': json['command'],
        'trainingParams': StartCommandTrainingParamsFromJSON(json['trainingParams']),
    };
}

export function StartCommandToJSON(value?: StartCommand): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'command': value.command,
        'trainingParams': StartCommandTrainingParamsToJSON(value.trainingParams),
    };
}

/**
* @export
* @enum {string}
*/
export enum StartCommandCommandEnum {
    Start = 'start'
}


