// tslint:disable
/**
 * Markku portal API
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: markku@futurice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface StartCommandTrainingParams
 */
export interface StartCommandTrainingParams {
    /**
     * 
     * @type {string}
     * @memberof StartCommandTrainingParams
     */
    modelName: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StartCommandTrainingParams
     */
    tubs: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof StartCommandTrainingParams
     */
    augmentations: Array<string>;
}

export function StartCommandTrainingParamsFromJSON(json: any): StartCommandTrainingParams {
    return {
        'modelName': json['modelName'],
        'tubs': json['tubs'],
        'augmentations': json['augmentations'],
    };
}

export function StartCommandTrainingParamsToJSON(value?: StartCommandTrainingParams): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'modelName': value.modelName,
        'tubs': value.tubs,
        'augmentations': value.augmentations,
    };
}


