// tslint:disable
/**
 * Markku portal API
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: markku@futurice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface StopCommand
 */
export interface StopCommand {
    /**
     * 
     * @type {string}
     * @memberof StopCommand
     */
    command: StopCommandCommandEnum;
}

export function StopCommandFromJSON(json: any): StopCommand {
    return {
        'command': json['command'],
    };
}

export function StopCommandToJSON(value?: StopCommand): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'command': value.command,
    };
}

/**
* @export
* @enum {string}
*/
export enum StopCommandCommandEnum {
    Stop = 'stop'
}


