// tslint:disable
/**
 * Markku portal API
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: markku@futurice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface Tub
 */
export interface Tub {
    /**
     * 
     * @type {string}
     * @memberof Tub
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Tub
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Tub
     */
    timestamp: Date;
    /**
     * 
     * @type {number}
     * @memberof Tub
     */
    numDataPoints: number;
}

export function TubFromJSON(json: any): Tub {
    return {
        'id': json['id'],
        'name': json['name'],
        'timestamp': new Date(json['timestamp']),
        'numDataPoints': json['numDataPoints'],
    };
}

export function TubToJSON(value?: Tub): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'timestamp': value.timestamp.toISOString(),
        'numDataPoints': value.numDataPoints,
    };
}


