// tslint:disable
/**
 * Markku portal API
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: markku@futurice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface TubDataPoint
 */
export interface TubDataPoint {
    /**
     * 
     * @type {Date}
     * @memberof TubDataPoint
     */
    timestamp: Date;
    /**
     * 
     * @type {number}
     * @memberof TubDataPoint
     */
    angle: number;
    /**
     * 
     * @type {number}
     * @memberof TubDataPoint
     */
    throttle: number;
    /**
     * 
     * @type {string}
     * @memberof TubDataPoint
     */
    imageName: string;
}

export function TubDataPointFromJSON(json: any): TubDataPoint {
    return {
        'timestamp': new Date(json['timestamp']),
        'angle': json['angle'],
        'throttle': json['throttle'],
        'imageName': json['imageName'],
    };
}

export function TubDataPointToJSON(value?: TubDataPoint): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'timestamp': value.timestamp.toISOString(),
        'angle': value.angle,
        'throttle': value.throttle,
        'imageName': value.imageName,
    };
}


